name: Build site

on: [ push, pull_request ]

jobs:
  build_and_run_tests:
    name: Build C# code and run tests
    runs-on: ubuntu-latest
    env:
      MY_OWN_STRING: ABC
      MY_OWN_STRING_WITH_SINGLE_QUOTES: 'ABC'
      MY_OWN_STRING_WITH_DOUBLE_QUOTES: "ABC"
      MY_OWN_INT: 1
      MY_OWN_INT_WITH_SINGLE_QUOTES: '1'
      MY_OWN_INT_WITH_DOUBLE_QUOTES: "1"
      MY_OWN_BOOL: true
      MY_OWN_BOOL_WITH_SINGLE_QUOTES: 'true'
      MY_OWN_BOOL_WITH_DOUBLE_QUOTES: "true"

    steps:
      - name: Dump relevant parts of Environment
        run:  env | grep MY_OWN | sort

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests from solution
        run: dotnet test --no-restore --no-build
